"""contract lifecycle baseline

Revision ID: 7d246ea44c29
Revises:
Create Date: 2026-09-17 15:10:30.098658
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d246ea44c29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor'), 'audit_events', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contract_type', sa.String(length=80), nullable=False),
    sa.Column('current_version', sa.String(length=20), nullable=False),
    sa.Column('last_modified', sa.Date(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('compliance', sa.String(length=30), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('risk', sa.String(length=10), nullable=False),
    sa.Column('counterparty', sa.String(length=200), nullable=False),
    sa.Column('jurisdiction', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_compliance'), 'contracts', ['compliance'], unique=False)
    op.create_index(op.f('ix_contracts_department'), 'contracts', ['department'], unique=False)
    op.create_index(op.f('ix_contracts_review_status'), 'contracts', ['review_status'], unique=False)
    op.create_table('expertise',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('obligations',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewers',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('workload', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assignments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=16), nullable=False),
    sa.Column('reviewer_id', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_contract_id'), 'assignments', ['contract_id'], unique=True)
    op.create_index(op.f('ix_assignments_reviewer_id'), 'assignments', ['reviewer_id'], unique=False)
    op.create_table('contract_versions',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('contract_id', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('version_date', sa.Date(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_media_type', sa.String(length=100), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'label')
    )
    op.create_index(op.f('ix_contract_versions_contract_id'), 'contract_versions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_versions_source_sha256'), 'contract_versions', ['source_sha256'], unique=False)
    op.create_table('reviewer_expertise',
    sa.Column('reviewer_id', sa.String(length=16), nullable=False),
    sa.Column('expertise_id', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['expertise_id'], ['expertise.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
    sa.PrimaryKeyConstraint('reviewer_id', 'expertise_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('contract_id', sa.String(length=16), nullable=False),
    sa.Column('reviewer_id', sa.String(length=16), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('issue', sa.String(length=300), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_contract_id'), 'reviews', ['contract_id'], unique=False)
    op.create_index(op.f('ix_reviews_priority'), 'reviews', ['priority'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_table('clauses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clause_key', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=16), nullable=False),
    sa.Column('version_id', sa.String(length=24), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=False),
    sa.Column('source_section', sa.String(length=160), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['contract_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'clause_key')
    )
    op.create_index(op.f('ix_clauses_clause_key'), 'clauses', ['clause_key'], unique=False)
    op.create_index(op.f('ix_clauses_contract_id'), 'clauses', ['contract_id'], unique=False)
    op.create_index(op.f('ix_clauses_status'), 'clauses', ['status'], unique=False)
    op.create_index(op.f('ix_clauses_tier'), 'clauses', ['tier'], unique=False)
    op.create_index(op.f('ix_clauses_version_id'), 'clauses', ['version_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('review_id', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_review_id'), 'review_decisions', ['review_id'], unique=True)
    op.create_table('clause_obligations',
    sa.Column('clause_id', sa.String(length=32), nullable=False),
    sa.Column('obligation_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('clause_id', 'obligation_id')
    )
    op.create_table('clause_tags',
    sa.Column('clause_id', sa.String(length=32), nullable=False),
    sa.Column('tag_id', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('clause_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clause_tags')
    op.drop_table('clause_obligations')
    op.drop_index(op.f('ix_review_decisions_review_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_clauses_version_id'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_tier'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_status'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_contract_id'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_clause_key'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_priority'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_contract_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('reviewer_expertise')
    op.drop_index(op.f('ix_contract_versions_source_sha256'), table_name='contract_versions')
    op.drop_index(op.f('ix_contract_versions_contract_id'), table_name='contract_versions')
    op.drop_table('contract_versions')
    op.drop_index(op.f('ix_assignments_reviewer_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_contract_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('tags')
    op.drop_table('settings')
    op.drop_table('reviewers')
    op.drop_table('obligations')
    op.drop_table('expertise')
    op.drop_index(op.f('ix_contracts_review_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_department'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_compliance'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
